"""add user_favorite_events

Revision ID: 42e96ddc41ad
Revises: 0002_users_auth_favs
Create Date: 2025-10-04 21:06:58.411239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0003_add_user_favorite_events'
down_revision: Union[str, Sequence[str], None] = '0002_users_auth_favs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorite_events',
    sa.Column('user_uuid', sa.BINARY(length=16), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_uuid', 'event_id')
    )
    op.alter_column('auth_token_families', 'uuid',
               existing_type=sa.NUMERIC(precision=16),
               type_=sa.BINARY(length=16),
               existing_nullable=False)
    op.alter_column('auth_token_families', 'last_refresh_token',
               existing_type=sa.NUMERIC(precision=16),
               type_=sa.BINARY(length=16),
               nullable=False)
    op.alter_column('auth_token_families', 'delete_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('auth_token_families', 'token_scopes',
               existing_type=sqlite.JSON(),
               nullable=False)
    op.alter_column('auth_token_families', 'user_uuid',
               existing_type=sa.NUMERIC(precision=16),
               type_=sa.BINARY(length=16),
               existing_nullable=False)
    op.create_index(op.f('ix_auth_token_families_uuid'), 'auth_token_families', ['uuid'], unique=False)
    op.alter_column('auth_token_families_revoked', 'uuid',
               existing_type=sa.NUMERIC(precision=16),
               type_=sa.BINARY(length=16),
               existing_nullable=False)
    op.alter_column('auth_token_families_revoked', 'delete_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_auth_token_families_revoked_uuid'), 'auth_token_families_revoked', ['uuid'], unique=False)
    op.alter_column('events', 'name',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('events', 'tickets_sales_start',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('events', 'tickets_sales_end',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('events', 'smtp_mail_from',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('events', 'mail_text_new_ticket',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    op.alter_column('events', 'mail_html_new_ticket',
               existing_type=sa.VARCHAR(length=2048),
               nullable=False)
    op.alter_column('events', 'mail_text_cancelled_ticket',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    op.alter_column('events', 'mail_html_cancelled_ticket',
               existing_type=sa.VARCHAR(length=2048),
               nullable=False)
    op.alter_column('ticket_groups', 'name',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('ticket_groups', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ticket_groups', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tickets', 'email',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('tickets', 'firstname',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('tickets', 'lastname',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('tickets', 'order_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('tickets', 'status',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    op.alter_column('tickets', 'description',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('tickets', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.alter_column('users', 'uuid',
               existing_type=sa.NUMERIC(precision=16),
               type_=sa.BINARY(length=16),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'disabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'scopes',
               existing_type=sqlite.JSON(),
               nullable=False)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.alter_column('users', 'scopes',
               existing_type=sqlite.JSON(),
               nullable=True)
    op.alter_column('users', 'disabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'uuid',
               existing_type=sa.BINARY(length=16),
               type_=sa.NUMERIC(precision=16),
               existing_nullable=False)
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.alter_column('tickets', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tickets', 'description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('tickets', 'status',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    op.alter_column('tickets', 'order_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('tickets', 'lastname',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('tickets', 'firstname',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('tickets', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('ticket_groups', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ticket_groups', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ticket_groups', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('events', 'mail_html_cancelled_ticket',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True)
    op.alter_column('events', 'mail_text_cancelled_ticket',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.alter_column('events', 'mail_html_new_ticket',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True)
    op.alter_column('events', 'mail_text_new_ticket',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.alter_column('events', 'smtp_mail_from',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('events', 'tickets_sales_end',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('events', 'tickets_sales_start',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('events', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=250),
               nullable=True)
    op.drop_index(op.f('ix_auth_token_families_revoked_uuid'), table_name='auth_token_families_revoked')
    op.alter_column('auth_token_families_revoked', 'delete_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('auth_token_families_revoked', 'uuid',
               existing_type=sa.BINARY(length=16),
               type_=sa.NUMERIC(precision=16),
               existing_nullable=False)
    op.drop_index(op.f('ix_auth_token_families_uuid'), table_name='auth_token_families')
    op.alter_column('auth_token_families', 'user_uuid',
               existing_type=sa.BINARY(length=16),
               type_=sa.NUMERIC(precision=16),
               existing_nullable=False)
    op.alter_column('auth_token_families', 'token_scopes',
               existing_type=sqlite.JSON(),
               nullable=True)
    op.alter_column('auth_token_families', 'delete_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('auth_token_families', 'last_refresh_token',
               existing_type=sa.BINARY(length=16),
               type_=sa.NUMERIC(precision=16),
               nullable=True)
    op.alter_column('auth_token_families', 'uuid',
               existing_type=sa.BINARY(length=16),
               type_=sa.NUMERIC(precision=16),
               existing_nullable=False)
    op.drop_table('user_favorite_events')
    # ### end Alembic commands ###
